CREATE TABLE GenderT (
	GenderId INT NOT NULL PRIMARY KEY,
	Male INT NOT NULL,
	Female INT NOT NULL
)

CREATE TABLE AgeRangeT (
	AgeId INT NOT NULL PRIMARY KEY,
	Under18 INT NOT NULL,
	YoungAdult INT NOT NULL,
	Adult INT NOT NULL,
	OlderAdult INT NOT NULL
)

CREATE TABLE OffenderT (
	OffenderId INT NOT NULL PRIMARY KEY,
	GenderId INT NOT NULL FOREIGN KEY REFERENCES GenderT(GenderId),
    AgeId INT NOT NULL FOREIGN KEY REFERENCES AgeRangeT(AgeId)
)

CREATE TABLE AboriginalityT (
	AboriginalityId INT NOT NULL PRIMARY KEY,
	Aboriginal INT NOT NULL,
	NonAboriginal INT NOT NULL
)

CREATE TABLE MonthT (
	MonthId INT NOT NULL PRIMARY KEY,
	January INT NOT NULL,
	February INT NOT NULL,
	March INT NOT NULL,
	April INT NOT NULL,
	May INT NOT NULL,
	June INT NOT NULL,
	July INT NOT NULL,
	August INT NOT NULL,
	September INT NOT NULL,
	October INT NOT NULL,
	November INT NOT NULL,
	December INT NOT NULL
)

CREATE TABLE TimeT (
	TimeId INT NOT NULL PRIMARY KEY,
	Morning INT NOT NULL,
	Afternoon INT NOT NULL,
	Evening INT NOT NULL,
	Night INT NOT NULL
)

CREATE TABLE OffenceT (
	OffenceId INT NOT NULL PRIMARY KEY,
	IncidentNo INT NOT NULL,
	MonthId INT NOT NULL FOREIGN KEY REFERENCES MonthT(MonthId),
	TimeId INT NOT NULL FOREIGN KEY REFERENCES TimeT(TimeId),
	AboriginalityId INT NOT NULL FOREIGN KEY REFERENCES AboriginalityT(AboriginalityId)
)

CREATE TABLE IndexesT (
	IndexId INT NOT NULL PRIMARY KEY,
	SEDis INT NOT NULL,
	SEDisAdv INT NOT NULL,
	EcoResources INT NOT NULL,
	EduOccupation INT NOT NULL
)

CREATE TABLE EIncomeT (
	EIncomeId INT NOT NULL PRIMARY KEY,
	MedianIncome INT NOT NULL
)

CREATE TABLE BenefitsT (
	BenefitsId INT NOT NULL PRIMARY KEY,
	HealthCareCard INT NOT NULL,
	JobSeekerPayment INT NOT NULL,
	LowIncomeCard INT NOT NULL,
	YouthAllowance INT NOT NULL
)

CREATE TABLE IncomeT (
	IncomeId INT NOT NULL PRIMARY KEY,
	EIncomeId INT NOT NULL FOREIGN KEY REFERENCES EIncomeT(EIncomeId),
	BenefitsId INT NOT NULL FOREIGN KEY REFERENCES BenefitsT(BenefitsId)
)

CREATE TABLE UnemploymentT (
	UnemploymentId INT NOT NULL PRIMARY KEY,
	AvgRate DECIMAL(4, 2) NOT NULL
)

CREATE TABLE PopulationT (
	PopulationId INT NOT NULL PRIMARY KEY,
	EstimatePop INT NOT NULL,
	IndigenousPop INT NOT NULL
)

CREATE TABLE LgaT (
	LgaId INT NOT NULL PRIMARY KEY,
	LgaName VARCHAR NOT NULL,
	OffenceId INT NOT NULL FOREIGN KEY REFERENCES OffenceT(OffenceId),
	IncomeId INT NOT NULL FOREIGN KEY REFERENCES IncomeT(IncomeId),
	IndexId INT NOT NULL FOREIGN KEY REFERENCES IndexesT(IndexId),
	PopulationId INT NOT NULL FOREIGN KEY REFERENCES PopulationT(PopulationId),
	UnemploymentId INT NOT NULL FOREIGN KEY REFERENCES UnemploymentT(UnemploymentId)
)